### PR TITLE
Data loading basic setup

### PR DESCRIPTION
**Pull request by pjsier**
# What's in this PR?

This is an initial stab at organizing our data loading process, both for local and production setup, that should be flexible for configuration and able to move more easily between Docker and production setups.

There are definitely more changes that need to be made, but because this has been a big issue I wanted to get it out here for people's feedback.

## Changes

* Created `loader.py`, which is using `subprocess` and `argparse` to manage the multiple different load steps without having to drop into shell scripts directly with configuration managed in `load_conf.json` files.
* Added some rough examples, changed naming conventions for some of the Pentaho scripts
* Made `loader.py` the entrypoint for the `etl` Docker container, and added some examples in the README to show how this changes loading

## To-Dos

* Still need to do a repo-wide naming convention update for states. There's no reason for us to be using the full names for states when we can use the postal abbrevation, and it makes handling configuration a lot easier.
* Deciding how to manage precinct loading, given that Washington in particular breaks the mold here.
* Document this more clearly, move instructions into the Docker README

## References

Progress on: #172

### CODE REVIEW

**Comment by JakeStevens** [comment]
An initial thought: get the current date and use that when loading if a report date is not given. I would assume that most report dates would be the current date, so may as well just use that as the default instead of excepting and exiting

**Comment by slavingia** [comment]
That, or we could force a report date, because if it takes a week to load in the data from the time we get it, that may be bad? Not sure.

**Comment by pjsier** [comment]
Updated to add the current date as a default for `report_date`, added a workaround for Washington, and cleaned up a bit. 

Two notes:
* Should we get rid of the `buildWashington.sh` and other build scripts now to keep things consistent?
* A lot of this depends on the naming conventions being updated. I'm happy to make another PR that changes all state folders to be the lower case postal abbreviation, does that sound good to people?

**Comment by slavingia** [comment]
yep, let's get rid of stuff like that since it'll confuse new people (and me!)

**Comment by BenGalewsky** [comment]
My preference is to drive this from a kettle job. I need to do this for New York. Let me try my hand at this for a bit and then propose how to move this all forward.

Thanks for taking this on!

**Pull request merged**
